In [41]:
import pandas as pd
import numpy as np
from datetime import datetime

In [42]:
df = pd.read_csv("visa_data.csv")
print(df)

     Application_ID Applicant_Country Visa_Type Processing_Office  \
0              1001               USA      Work            London
1              1002            Canada   Tourist               NaN
2              1003            France   Tourist           Toronto
3              1004            Canada   Student         New Delhi
4              1005           Germany      Work         Hyderabad
..              ...               ...       ...               ...
144            1145               USA      Work            London
145            1146           Germany   Tourist         Hyderabad
146            1147               USA   Tourist           Toronto
147            1148               NaN      Work         New Delhi
148            1149         Australia   Tourist         New Delhi

    Application_Date Decision_Date  Applicant_Age  Experience_Years
0         2022-03-19    2022-06-26             62              22.0
1         2022-06-06    2022-08-28            111               NaN
2         2022-03-09    2022-05-11            101              25.0
3         2022-02-27    2022-06-18            108               0.0
4         2022-09-03    2022-09-26             60              24.0
..               ...           ...            ...               ...
144       2022-01-06    2022-04-16             44               NaN
145       2022-12-18    2023-03-04             81               8.0
146       2022-03-18    2022-04-03            115              20.0
147       2022-01-10    2022-04-16             87               NaN
148       2022-11-06    2022-11-24            111               NaN

[149 rows x 8 columns]

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Application_ID     149 non-null    int64
 1   Applicant_Country  125 non-null    object
 2   Visa_Type          149 non-null    object
 3   Processing_Office  126 non-null    object
 4   Application_Date   149 non-null    object
 5   Decision_Date      148 non-null    object
 6   Applicant_Age      149 non-null    int64
 7   Experience_Years   69 non-null     float64
dtypes: float64(1), int64(2), object(5)
memory usage: 9.4+ KB

In [44]:
df.isnull().sum()

Application_ID        0
Applicant_Country    24
Visa_Type             0
Processing_Office    23
Application_Date      0
Decision_Date         1
Applicant_Age         0
Experience_Years     80
dtype: int64

In [45]:
#categorical
df['Applicant_Country'] = df['Applicant_Country'].fillna("Unknown")
df['Processing_Office'] = df['Processing_Office'].fillna("Unknown")
print(df)

     Application_ID Applicant_Country Visa_Type Processing_Office  \
0              1001               USA      Work            London
1              1002            Canada   Tourist           Unknown
2              1003            France   Tourist           Toronto
3              1004            Canada   Student         New Delhi
4              1005           Germany      Work         Hyderabad
..              ...               ...       ...               ...
144            1145               USA      Work            London
145            1146           Germany   Tourist         Hyderabad
146            1147               USA   Tourist           Toronto
147            1148           Unknown      Work         New Delhi
148            1149         Australia   Tourist         New Delhi

    Application_Date Decision_Date  Applicant_Age  Experience_Years
0         2022-03-19    2022-06-26             62              22.0
1         2022-06-06    2022-08-28            111               NaN
2         2022-03-09    2022-05-11            101              25.0
3         2022-02-27    2022-06-18            108               0.0
4         2022-09-03    2022-09-26             60              24.0
..               ...           ...            ...               ...
144       2022-01-06    2022-04-16             44               NaN
145       2022-12-18    2023-03-04             81               8.0
146       2022-03-18    2022-04-03            115              20.0
147       2022-01-10    2022-04-16             87               NaN
148       2022-11-06    2022-11-24            111               NaN

[149 rows x 8 columns]

In [46]:
#numerical
df['Experience_Years'] = df['Experience_Years'].fillna(df['Experience_Years'].median())
print(df)

     Application_ID Applicant_Country Visa_Type Processing_Office  \
0              1001               USA      Work            London
1              1002            Canada   Tourist           Unknown
2              1003            France   Tourist           Toronto
3              1004            Canada   Student         New Delhi
4              1005           Germany      Work         Hyderabad
..              ...               ...       ...               ...
144            1145               USA      Work            London
145            1146           Germany   Tourist         Hyderabad
146            1147               USA   Tourist           Toronto
147            1148           Unknown      Work         New Delhi
148            1149         Australia   Tourist         New Delhi

    Application_Date Decision_Date  Applicant_Age  Experience_Years
0         2022-03-19    2022-06-26             62              22.0
1         2022-06-06    2022-08-28            111              12.0
2         2022-03-09    2022-05-11            101              25.0
3         2022-02-27    2022-06-18            108               0.0
4         2022-09-03    2022-09-26             60              24.0
..               ...           ...            ...               ...
144       2022-01-06    2022-04-16             44              12.0
145       2022-12-18    2023-03-04             81               8.0
146       2022-03-18    2022-04-03            115              20.0
147       2022-01-10    2022-04-16             87              12.0
148       2022-11-06    2022-11-24            111              12.0

[149 rows x 8 columns]

In [47]:
# decision date is mandatory for target calculation
df.dropna(subset=['Decision_Date'], inplace=True)
print(df)

     Application_ID Applicant_Country Visa_Type Processing_Office  \
0              1001               USA      Work            London
1              1002            Canada   Tourist           Unknown
2              1003            France   Tourist           Toronto
3              1004            Canada   Student         New Delhi
4              1005           Germany      Work         Hyderabad
..              ...               ...       ...               ...
144            1145               USA      Work            London
145            1146           Germany   Tourist         Hyderabad
146            1147               USA   Tourist           Toronto
147            1148           Unknown      Work         New Delhi
148            1149         Australia   Tourist         New Delhi

    Application_Date Decision_Date  Applicant_Age  Experience_Years
0         2022-03-19    2022-06-26             62              22.0
1         2022-06-06    2022-08-28            111              12.0
2         2022-03-09    2022-05-11            101              25.0
3         2022-02-27    2022-06-18            108               0.0
4         2022-09-03    2022-09-26             60              24.0
..               ...           ...            ...               ...
144       2022-01-06    2022-04-16             44              12.0
145       2022-12-18    2023-03-04             81               8.0
146       2022-03-18    2022-04-03            115              20.0
147       2022-01-10    2022-04-16             87              12.0
148       2022-11-06    2022-11-24            111              12.0

[148 rows x 8 columns]

In [48]:
df['Application_Date'] = pd.to_datetime(df['Application_Date'], errors='coerce')
df['Decision_Date'] = pd.to_datetime(df['Decision_Date'], errors='coerce')

df.dropna(subset=['Application_Date', 'Decision_Date'], inplace=True)
print(df)

     Application_ID Applicant_Country Visa_Type Processing_Office  \
0              1001               USA      Work            London
1              1002            Canada   Tourist           Unknown
2              1003            France   Tourist           Toronto
3              1004            Canada   Student         New Delhi
4              1005           Germany      Work         Hyderabad
..              ...               ...       ...               ...
144            1145               USA      Work            London
145            1146           Germany   Tourist         Hyderabad
146            1147               USA   Tourist           Toronto
147            1148           Unknown      Work         New Delhi
148            1149         Australia   Tourist         New Delhi

    Application_Date Decision_Date  Applicant_Age  Experience_Years
0         2022-03-19    2022-06-26             62              22.0
1         2022-06-06    2022-08-28            111              12.0
2         2022-03-09    2022-05-11            101              25.0
3         2022-02-27    2022-06-18            108               0.0
4         2022-09-03    2022-09-26             60              24.0
..               ...           ...            ...               ...
144       2022-01-06    2022-04-16             44              12.0
145       2022-12-18    2023-03-04             81               8.0
146       2022-03-18    2022-04-03            115              20.0
147       2022-01-10    2022-04-16             87              12.0
148       2022-11-06    2022-11-24            111              12.0

[143 rows x 8 columns]

In [49]:
#removing invalid age values
df = df[(df['Applicant_Age'] > 0) & (df['Applicant_Age'] < 100)]
print(df)

     Application_ID Applicant_Country Visa_Type Processing_Office  \
0              1001               USA      Work            London
4              1005           Germany      Work         Hyderabad
5              1006           Germany   Student           Unknown
6              1007               USA   Tourist            London
7              1008           Germany   Student         Hyderabad
..              ...               ...       ...               ...
142            1143            Canada   Tourist            Sydney
143            1144         Australia   Student            Sydney
144            1145               USA      Work            London
145            1146           Germany   Tourist         Hyderabad
147            1148           Unknown      Work         New Delhi

    Application_Date Decision_Date  Applicant_Age  Experience_Years
0         2022-03-19    2022-06-26             62              22.0
4         2022-09-03    2022-09-26             60              24.0
5         2022-11-28    2022-12-08             75              19.0
6         2022-03-25    2022-06-30             63               4.0
7         2022-04-04    2022-04-04             71              12.0
..               ...           ...            ...               ...
142       2022-03-16    2022-04-04             86              12.0
143       2022-03-15    2022-07-02             96              12.0
144       2022-01-06    2022-04-16             44              12.0
145       2022-12-18    2023-03-04             81               8.0
147       2022-01-10    2022-04-16             87              12.0

[99 rows x 8 columns]

In [50]:
df = df[(df['Applicant_Age'] >= 18) & (df['Applicant_Age'] <= 75)]
df

,Application_ID,Applicant_Country,Visa_Type,Processing_Office,Application_Date,Decision_Date,Applicant_Age,Experience_Years
0,1001,USA,Work,London,2022-03-19,2022-06-26,62,22.0
4,1005,Germany,Work,Hyderabad,2022-09-03,2022-09-26,60,24.0
5,1006,Germany,Student,Unknown,2022-11-28,2022-12-08,75,19.0
6,1007,USA,Tourist,London,2022-03-25,2022-06-30,63,4.0
7,1008,Germany,Student,Hyderabad,2022-04-04,2022-04-04,71,12.0
8,1009,Australia,Tourist,Unknown,2022-08-23,2022-09-13,26,12.0
9,1010,Unknown,Work,Unknown,2022-09-08,2022-10-03,48,24.0
10,1011,UK,Student,Unknown,2022-12-23,2023-02-23,35,12.0
13,1014,USA,Work,Unknown,2022-03-31,2022-04-03,35,12.0
19,1020,Canada,Tourist,Toronto,2022-12-21,2022-12-26,37,12.0
20,1021,India,Tourist,New Delhi,2022-04-07,2022-06-12,26,13.0
24,1025,UK,Work,Hyderabad,2022-01-24,2022-01-23,42,5.0
26,1027,Unknown,Work,Hyderabad,2022-10-15,2023-01-19,52,8.0
30,1031,Germany,Student,Unknown,2022-03-25,2022-06-27,56,16.0
33,1034,Australia,Tourist,California,2022-09-06,2022-10-01,25,12.0
34,1035,Unknown,Work,California,2022-08-06,2022-09-22,72,10.0
35,1036,UK,Tourist,New Delhi,2022-11-20,2022-12-19,56,19.0
38,1039,USA,Tourist,Unknown,2022-08-11,2022-08-19,67,12.0
39,1040,Canada,Tourist,Toronto,2022-03-14,2022-06-08,44,17.0
40,1041,USA,Work,Hyderabad,2022-02-24,2022-03-17,29,3.0
43,1044,UK,Tourist,London,2022-01-22,2022-01-18,45,12.0
44,1045,Germany,Work,Hyderabad,2022-11-11,2023-03-05,29,12.0
46,1047,Unknown,Tourist,London,2022-12-16,2023-03-24,34,12.0
49,1050,Unknown,Tourist,New Delhi,2022-12-05,2022-12-23,43,23.0
50,1051,UK,Work,Hyderabad,2022-05-04,2022-07-29,36,12.0
54,1055,Canada,Work,New Delhi,2022-12-24,2023-04-09,65,12.0
55,1056,Australia,Work,California,2022-12-11,2023-02-22,47,22.0
58,1059,Unknown,Student,London,2022-10-29,2023-02-02,42,4.0
59,1060,USA,Tourist,London,2022-01-11,2022-02-20,34,12.0
60,1061,France,Student,Hyderabad,2022-06-29,2022-09-13,63,12.0
62,1063,Canada,Work,California,2022-08-23,2022-11-26,75,12.0
68,1069,France,Tourist,Unknown,2022-09-23,2022-09-19,68,5.0
69,1070,USA,Work,Toronto,2022-03-16,2022-03-12,30,12.0
72,1073,Canada,Work,Sydney,2022-04-13,2022-08-07,38,7.0
79,1080,France,Tourist,California,2022-02-08,2022-06-04,50,25.0
84,1085,Canada,Work,London,2022-08-11,2022-10-27,65,12.0
85,1086,Unknown,Tourist,Unknown,2022-10-01,2023-01-01,62,12.0
86,1087,UK,Work,Toronto,2022-05-24,2022-09-05,18,4.0
97,1098,France,Tourist,Sydney,2022-04-02,2022-04-21,20,18.0
102,1103,Australia,Tourist,Hyderabad,2022-12-08,2022-12-09,74,12.0
106,1107,Australia,Tourist,Sydney,2022-05-09,2022-06-30,54,12.0
107,1108,Canada,Tourist,California,2022-07-01,2022-07-31,20,12.0
111,1112,UK,Student,Sydney,2022-05-11,2022-05-10,73,1.0
113,1114,USA,Tourist,Unknown,2022-12-23,2023-03-16,47,12.0
115,1116,Unknown,Tourist,California,2022-08-08,2022-10-11,44,21.0
116,1117,USA,Work,New Delhi,2022-07-24,2022-08-24,58,12.0
117,1118,Canada,Student,New Delhi,2022-06-01,2022-07-07,64,12.0
118,1119,India,Tourist,Toronto,2022-12-19,2023-03-12,74,21.0
119,1120,Canada,Work,California,2022-08-08,2022-11-30,42,12.0
121,1122,France,Work,Sydney,2022-07-09,2022-07-13,28,12.0
124,1125,India,Student,Toronto,2022-10-08,2022-11-20,48,4.0
128,1129,Australia,Student,London,2022-09-19,2022-12-26,55,5.0
138,1139,Unknown,Tourist,Unknown,2022-07-17,2022-08-10,20,12.0
144,1145,USA,Work,London,2022-01-06,2022-04-16,44,12.0

In [51]:
df = df[df['Experience_Years'] <= df['Applicant_Age']]
df

,Application_ID,Applicant_Country,Visa_Type,Processing_Office,Application_Date,Decision_Date,Applicant_Age,Experience_Years
0,1001,USA,Work,London,2022-03-19,2022-06-26,62,22.0
4,1005,Germany,Work,Hyderabad,2022-09-03,2022-09-26,60,24.0
5,1006,Germany,Student,Unknown,2022-11-28,2022-12-08,75,19.0
6,1007,USA,Tourist,London,2022-03-25,2022-06-30,63,4.0
7,1008,Germany,Student,Hyderabad,2022-04-04,2022-04-04,71,12.0
8,1009,Australia,Tourist,Unknown,2022-08-23,2022-09-13,26,12.0
9,1010,Unknown,Work,Unknown,2022-09-08,2022-10-03,48,24.0
10,1011,UK,Student,Unknown,2022-12-23,2023-02-23,35,12.0
13,1014,USA,Work,Unknown,2022-03-31,2022-04-03,35,12.0
19,1020,Canada,Tourist,Toronto,2022-12-21,2022-12-26,37,12.0
20,1021,India,Tourist,New Delhi,2022-04-07,2022-06-12,26,13.0
24,1025,UK,Work,Hyderabad,2022-01-24,2022-01-23,42,5.0
26,1027,Unknown,Work,Hyderabad,2022-10-15,2023-01-19,52,8.0
30,1031,Germany,Student,Unknown,2022-03-25,2022-06-27,56,16.0
33,1034,Australia,Tourist,California,2022-09-06,2022-10-01,25,12.0
34,1035,Unknown,Work,California,2022-08-06,2022-09-22,72,10.0
35,1036,UK,Tourist,New Delhi,2022-11-20,2022-12-19,56,19.0
38,1039,USA,Tourist,Unknown,2022-08-11,2022-08-19,67,12.0
39,1040,Canada,Tourist,Toronto,2022-03-14,2022-06-08,44,17.0
40,1041,USA,Work,Hyderabad,2022-02-24,2022-03-17,29,3.0
43,1044,UK,Tourist,London,2022-01-22,2022-01-18,45,12.0
44,1045,Germany,Work,Hyderabad,2022-11-11,2023-03-05,29,12.0
46,1047,Unknown,Tourist,London,2022-12-16,2023-03-24,34,12.0
49,1050,Unknown,Tourist,New Delhi,2022-12-05,2022-12-23,43,23.0
50,1051,UK,Work,Hyderabad,2022-05-04,2022-07-29,36,12.0
54,1055,Canada,Work,New Delhi,2022-12-24,2023-04-09,65,12.0
55,1056,Australia,Work,California,2022-12-11,2023-02-22,47,22.0
58,1059,Unknown,Student,London,2022-10-29,2023-02-02,42,4.0
59,1060,USA,Tourist,London,2022-01-11,2022-02-20,34,12.0
60,1061,France,Student,Hyderabad,2022-06-29,2022-09-13,63,12.0
62,1063,Canada,Work,California,2022-08-23,2022-11-26,75,12.0
68,1069,France,Tourist,Unknown,2022-09-23,2022-09-19,68,5.0
69,1070,USA,Work,Toronto,2022-03-16,2022-03-12,30,12.0
72,1073,Canada,Work,Sydney,2022-04-13,2022-08-07,38,7.0
79,1080,France,Tourist,California,2022-02-08,2022-06-04,50,25.0
84,1085,Canada,Work,London,2022-08-11,2022-10-27,65,12.0
85,1086,Unknown,Tourist,Unknown,2022-10-01,2023-01-01,62,12.0
86,1087,UK,Work,Toronto,2022-05-24,2022-09-05,18,4.0
97,1098,France,Tourist,Sydney,2022-04-02,2022-04-21,20,18.0
102,1103,Australia,Tourist,Hyderabad,2022-12-08,2022-12-09,74,12.0
106,1107,Australia,Tourist,Sydney,2022-05-09,2022-06-30,54,12.0
107,1108,Canada,Tourist,California,2022-07-01,2022-07-31,20,12.0
111,1112,UK,Student,Sydney,2022-05-11,2022-05-10,73,1.0
113,1114,USA,Tourist,Unknown,2022-12-23,2023-03-16,47,12.0
115,1116,Unknown,Tourist,California,2022-08-08,2022-10-11,44,21.0
116,1117,USA,Work,New Delhi,2022-07-24,2022-08-24,58,12.0
117,1118,Canada,Student,New Delhi,2022-06-01,2022-07-07,64,12.0
118,1119,India,Tourist,Toronto,2022-12-19,2023-03-12,74,21.0
119,1120,Canada,Work,California,2022-08-08,2022-11-30,42,12.0
121,1122,France,Work,Sydney,2022-07-09,2022-07-13,28,12.0
124,1125,India,Student,Toronto,2022-10-08,2022-11-20,48,4.0
128,1129,Australia,Student,London,2022-09-19,2022-12-26,55,5.0
138,1139,Unknown,Tourist,Unknown,2022-07-17,2022-08-10,20,12.0
144,1145,USA,Work,London,2022-01-06,2022-04-16,44,12.0

In [52]:
df.replace("Unknown", pd.NA, inplace=True)
df.dropna(inplace=True)
df

,Application_ID,Applicant_Country,Visa_Type,Processing_Office,Application_Date,Decision_Date,Applicant_Age,Experience_Years
0,1001,USA,Work,London,2022-03-19,2022-06-26,62,22.0
4,1005,Germany,Work,Hyderabad,2022-09-03,2022-09-26,60,24.0
6,1007,USA,Tourist,London,2022-03-25,2022-06-30,63,4.0
7,1008,Germany,Student,Hyderabad,2022-04-04,2022-04-04,71,12.0
19,1020,Canada,Tourist,Toronto,2022-12-21,2022-12-26,37,12.0
20,1021,India,Tourist,New Delhi,2022-04-07,2022-06-12,26,13.0
24,1025,UK,Work,Hyderabad,2022-01-24,2022-01-23,42,5.0
33,1034,Australia,Tourist,California,2022-09-06,2022-10-01,25,12.0
35,1036,UK,Tourist,New Delhi,2022-11-20,2022-12-19,56,19.0
39,1040,Canada,Tourist,Toronto,2022-03-14,2022-06-08,44,17.0
40,1041,USA,Work,Hyderabad,2022-02-24,2022-03-17,29,3.0
43,1044,UK,Tourist,London,2022-01-22,2022-01-18,45,12.0
44,1045,Germany,Work,Hyderabad,2022-11-11,2023-03-05,29,12.0
50,1051,UK,Work,Hyderabad,2022-05-04,2022-07-29,36,12.0
54,1055,Canada,Work,New Delhi,2022-12-24,2023-04-09,65,12.0
55,1056,Australia,Work,California,2022-12-11,2023-02-22,47,22.0
59,1060,USA,Tourist,London,2022-01-11,2022-02-20,34,12.0
60,1061,France,Student,Hyderabad,2022-06-29,2022-09-13,63,12.0
62,1063,Canada,Work,California,2022-08-23,2022-11-26,75,12.0
69,1070,USA,Work,Toronto,2022-03-16,2022-03-12,30,12.0
72,1073,Canada,Work,Sydney,2022-04-13,2022-08-07,38,7.0
79,1080,France,Tourist,California,2022-02-08,2022-06-04,50,25.0
84,1085,Canada,Work,London,2022-08-11,2022-10-27,65,12.0
86,1087,UK,Work,Toronto,2022-05-24,2022-09-05,18,4.0
97,1098,France,Tourist,Sydney,2022-04-02,2022-04-21,20,18.0
102,1103,Australia,Tourist,Hyderabad,2022-12-08,2022-12-09,74,12.0
106,1107,Australia,Tourist,Sydney,2022-05-09,2022-06-30,54,12.0
107,1108,Canada,Tourist,California,2022-07-01,2022-07-31,20,12.0
111,1112,UK,Student,Sydney,2022-05-11,2022-05-10,73,1.0
116,1117,USA,Work,New Delhi,2022-07-24,2022-08-24,58,12.0
117,1118,Canada,Student,New Delhi,2022-06-01,2022-07-07,64,12.0
118,1119,India,Tourist,Toronto,2022-12-19,2023-03-12,74,21.0
119,1120,Canada,Work,California,2022-08-08,2022-11-30,42,12.0
121,1122,France,Work,Sydney,2022-07-09,2022-07-13,28,12.0
124,1125,India,Student,Toronto,2022-10-08,2022-11-20,48,4.0
128,1129,Australia,Student,London,2022-09-19,2022-12-26,55,5.0
144,1145,USA,Work,London,2022-01-06,2022-04-16,44,12.0

In [53]:
# Convert dates
df['Application_Date'] = pd.to_datetime(df['Application_Date'], errors='coerce')
df['Decision_Date'] = pd.to_datetime(df['Decision_Date'], errors='coerce')

In [54]:
#Create Target Variable
df['Processing_Time_Days'] = (df['Decision_Date'] - df['Application_Date']).dt.days
print("\n After calculating processing days:\n", df)
print(df)

 After calculating processing days:
      Application_ID Applicant_Country Visa_Type Processing_Office  \
0              1001               USA      Work            London
4              1005           Germany      Work         Hyderabad
6              1007               USA   Tourist            London
7              1008           Germany   Student         Hyderabad
19             1020            Canada   Tourist           Toronto
20             1021             India   Tourist         New Delhi
24             1025                UK      Work         Hyderabad
33             1034         Australia   Tourist        California
35             1036                UK   Tourist         New Delhi
39             1040            Canada   Tourist           Toronto
40             1041               USA      Work         Hyderabad
43             1044                UK   Tourist            London
44             1045           Germany      Work         Hyderabad
50             1051                UK      Work         Hyderabad
54             1055            Canada      Work         New Delhi
55             1056         Australia      Work        California
59             1060               USA   Tourist            London
60             1061            France   Student         Hyderabad
62             1063            Canada      Work        California
69             1070               USA      Work           Toronto
72             1073            Canada      Work            Sydney
79             1080            France   Tourist        California
84             1085            Canada      Work            London
86             1087                UK      Work           Toronto
97             1098            France   Tourist            Sydney
102            1103         Australia   Tourist         Hyderabad
106            1107         Australia   Tourist            Sydney
107            1108            Canada   Tourist        California
111            1112                UK   Student            Sydney
116            1117               USA      Work         New Delhi
117            1118            Canada   Student         New Delhi
118            1119             India   Tourist           Toronto
119            1120            Canada      Work        California
121            1122            France      Work            Sydney
124            1125             India   Student           Toronto
128            1129         Australia   Student            London
144            1145               USA      Work            London

    Application_Date Decision_Date  Applicant_Age  Experience_Years  \
0         2022-03-19    2022-06-26             62              22.0
4         2022-09-03    2022-09-26             60              24.0
6         2022-03-25    2022-06-30             63               4.0
7         2022-04-04    2022-04-04             71              12.0
19        2022-12-21    2022-12-26             37              12.0
20        2022-04-07    2022-06-12             26              13.0
24        2022-01-24    2022-01-23             42               5.0
33        2022-09-06    2022-10-01             25              12.0
35        2022-11-20    2022-12-19             56              19.0
39        2022-03-14    2022-06-08             44              17.0
40        2022-02-24    2022-03-17             29               3.0
43        2022-01-22    2022-01-18             45              12.0
44        2022-11-11    2023-03-05             29              12.0
50        2022-05-04    2022-07-29             36              12.0
54        2022-12-24    2023-04-09             65              12.0
55        2022-12-11    2023-02-22             47              22.0
59        2022-01-11    2022-02-20             34              12.0
60        2022-06-29    2022-09-13             63              12.0
62        2022-08-23    2022-11-26             75              12.0
69        2022-03-16    2022-03-12             30              12.0
72        2022-04-13    2022-08-07             38               7.0
79        2022-02-08    2022-06-04             50              25.0
84        2022-08-11    2022-10-27             65              12.0
86        2022-05-24    2022-09-05             18               4.0
97        2022-04-02    2022-04-21             20              18.0
102       2022-12-08    2022-12-09             74              12.0
106       2022-05-09    2022-06-30             54              12.0
107       2022-07-01    2022-07-31             20              12.0
111       2022-05-11    2022-05-10             73               1.0
116       2022-07-24    2022-08-24             58              12.0
117       2022-06-01    2022-07-07             64              12.0
118       2022-12-19    2023-03-12             74              21.0
119       2022-08-08    2022-11-30             42              12.0
121       2022-07-09    2022-07-13             28              12.0
124       2022-10-08    2022-11-20             48               4.0
128       2022-09-19    2022-12-26             55               5.0
144       2022-01-06    2022-04-16             44              12.0

     Processing_Time_Days
0                      99
4                      23
6                      97
7                       0
19                      5
20                     66
24                     -1
33                     25
35                     29
39                     86
40                     21
43                     -4
44                    114
50                     86
54                    106
55                     73
59                     40
60                     76
62                     95
69                     -4
72                    116
79                    116
84                     77
86                    104
97                     19
102                     1
106                    52
107                    30
111                    -1
116                    31
117                    36
118                    83
119                   114
121                     4
124                    43
128                    98
144                   100
     Application_ID Applicant_Country Visa_Type Processing_Office  \
0              1001               USA      Work            London
4              1005           Germany      Work         Hyderabad
6              1007               USA   Tourist            London
7              1008           Germany   Student         Hyderabad
19             1020            Canada   Tourist           Toronto
20             1021             India   Tourist         New Delhi
24             1025                UK      Work         Hyderabad
33             1034         Australia   Tourist        California
35             1036                UK   Tourist         New Delhi
39             1040            Canada   Tourist           Toronto
40             1041               USA      Work         Hyderabad
43             1044                UK   Tourist            London
44             1045           Germany      Work         Hyderabad
50             1051                UK      Work         Hyderabad
54             1055            Canada      Work         New Delhi
55             1056         Australia      Work        California
59             1060               USA   Tourist            London
60             1061            France   Student         Hyderabad
62             1063            Canada      Work        California
69             1070               USA      Work           Toronto
72             1073            Canada      Work            Sydney
79             1080            France   Tourist        California
84             1085            Canada      Work            London
86             1087                UK      Work           Toronto
97             1098            France   Tourist            Sydney
102            1103         Australia   Tourist         Hyderabad
106            1107         Australia   Tourist            Sydney
107            1108            Canada   Tourist        California
111            1112                UK   Student            Sydney
116            1117               USA      Work         New Delhi
117            1118            Canada   Student         New Delhi
118            1119             India   Tourist           Toronto
119            1120            Canada      Work        California
121            1122            France      Work            Sydney
124            1125             India   Student           Toronto
128            1129         Australia   Student            London
144            1145               USA      Work            London

    Application_Date Decision_Date  Applicant_Age  Experience_Years  \
0         2022-03-19    2022-06-26             62              22.0
4         2022-09-03    2022-09-26             60              24.0
6         2022-03-25    2022-06-30             63               4.0
7         2022-04-04    2022-04-04             71              12.0
19        2022-12-21    2022-12-26             37              12.0
20        2022-04-07    2022-06-12             26              13.0
24        2022-01-24    2022-01-23             42               5.0
33        2022-09-06    2022-10-01             25              12.0
35        2022-11-20    2022-12-19             56              19.0
39        2022-03-14    2022-06-08             44              17.0
40        2022-02-24    2022-03-17             29               3.0
43        2022-01-22    2022-01-18             45              12.0
44        2022-11-11    2023-03-05             29              12.0
50        2022-05-04    2022-07-29             36              12.0
54        2022-12-24    2023-04-09             65              12.0
55        2022-12-11    2023-02-22             47              22.0
59        2022-01-11    2022-02-20             34              12.0
60        2022-06-29    2022-09-13             63              12.0
62        2022-08-23    2022-11-26             75              12.0
69        2022-03-16    2022-03-12             30              12.0
72        2022-04-13    2022-08-07             38               7.0
79        2022-02-08    2022-06-04             50              25.0
84        2022-08-11    2022-10-27             65              12.0
86        2022-05-24    2022-09-05             18               4.0
97        2022-04-02    2022-04-21             20              18.0
102       2022-12-08    2022-12-09             74              12.0
106       2022-05-09    2022-06-30             54              12.0
107       2022-07-01    2022-07-31             20              12.0
111       2022-05-11    2022-05-10             73               1.0
116       2022-07-24    2022-08-24             58              12.0
117       2022-06-01    2022-07-07             64              12.0
118       2022-12-19    2023-03-12             74              21.0
119       2022-08-08    2022-11-30             42              12.0
121       2022-07-09    2022-07-13             28              12.0
124       2022-10-08    2022-11-20             48               4.0
128       2022-09-19    2022-12-26             55               5.0
144       2022-01-06    2022-04-16             44              12.0

     Processing_Time_Days
0                      99
4                      23
6                      97
7                       0
19                      5
20                     66
24                     -1
33                     25
35                     29
39                     86
40                     21
43                     -4
44                    114
50                     86
54                    106
55                     73
59                     40
60                     76
62                     95
69                     -4
72                    116
79                    116
84                     77
86                    104
97                     19
102                     1
106                    52
107                    30
111                    -1
116                    31
117                    36
118                    83
119                   114
121                     4
124                    43
128                    98
144                   100

In [55]:
df['Processing_Time_Days'] = pd.to_numeric(df['Processing_Time_Days'], errors='coerce')

In [56]:
# Remove negative processing times
df = df[df['Processing_Time_Days'] > 0]
print(df)

     Application_ID Applicant_Country Visa_Type Processing_Office  \
0              1001               USA      Work            London
4              1005           Germany      Work         Hyderabad
6              1007               USA   Tourist            London
19             1020            Canada   Tourist           Toronto
20             1021             India   Tourist         New Delhi
33             1034         Australia   Tourist        California
35             1036                UK   Tourist         New Delhi
39             1040            Canada   Tourist           Toronto
40             1041               USA      Work         Hyderabad
44             1045           Germany      Work         Hyderabad
50             1051                UK      Work         Hyderabad
54             1055            Canada      Work         New Delhi
55             1056         Australia      Work        California
59             1060               USA   Tourist            London
60             1061            France   Student         Hyderabad
62             1063            Canada      Work        California
72             1073            Canada      Work            Sydney
79             1080            France   Tourist        California
84             1085            Canada      Work            London
86             1087                UK      Work           Toronto
97             1098            France   Tourist            Sydney
102            1103         Australia   Tourist         Hyderabad
106            1107         Australia   Tourist            Sydney
107            1108            Canada   Tourist        California
116            1117               USA      Work         New Delhi
117            1118            Canada   Student         New Delhi
118            1119             India   Tourist           Toronto
119            1120            Canada      Work        California
121            1122            France      Work            Sydney
124            1125             India   Student           Toronto
128            1129         Australia   Student            London
144            1145               USA      Work            London

    Application_Date Decision_Date  Applicant_Age  Experience_Years  \
0         2022-03-19    2022-06-26             62              22.0
4         2022-09-03    2022-09-26             60              24.0
6         2022-03-25    2022-06-30             63               4.0
19        2022-12-21    2022-12-26             37              12.0
20        2022-04-07    2022-06-12             26              13.0
33        2022-09-06    2022-10-01             25              12.0
35        2022-11-20    2022-12-19             56              19.0
39        2022-03-14    2022-06-08             44              17.0
40        2022-02-24    2022-03-17             29               3.0
44        2022-11-11    2023-03-05             29              12.0
50        2022-05-04    2022-07-29             36              12.0
54        2022-12-24    2023-04-09             65              12.0
55        2022-12-11    2023-02-22             47              22.0
59        2022-01-11    2022-02-20             34              12.0
60        2022-06-29    2022-09-13             63              12.0
62        2022-08-23    2022-11-26             75              12.0
72        2022-04-13    2022-08-07             38               7.0
79        2022-02-08    2022-06-04             50              25.0
84        2022-08-11    2022-10-27             65              12.0
86        2022-05-24    2022-09-05             18               4.0
97        2022-04-02    2022-04-21             20              18.0
102       2022-12-08    2022-12-09             74              12.0
106       2022-05-09    2022-06-30             54              12.0
107       2022-07-01    2022-07-31             20              12.0
116       2022-07-24    2022-08-24             58              12.0
117       2022-06-01    2022-07-07             64              12.0
118       2022-12-19    2023-03-12             74              21.0
119       2022-08-08    2022-11-30             42              12.0
121       2022-07-09    2022-07-13             28              12.0
124       2022-10-08    2022-11-20             48               4.0
128       2022-09-19    2022-12-26             55               5.0
144       2022-01-06    2022-04-16             44              12.0

     Processing_Time_Days
0                      99
4                      23
6                      97
19                      5
20                     66
33                     25
35                     29
39                     86
40                     21
44                    114
50                     86
54                    106
55                     73
59                     40
60                     76
62                     95
72                    116
79                    116
84                     77
86                    104
97                     19
102                     1
106                    52
107                    30
116                    31
117                    36
118                    83
119                   114
121                     4
124                    43
128                    98
144                   100

In [57]:
df.drop(columns=['Application_ID'], inplace=True , errors= 'ignore')
print(df)

    Applicant_Country Visa_Type Processing_Office Application_Date  \
0                 USA      Work            London       2022-03-19
4             Germany      Work         Hyderabad       2022-09-03
6                 USA   Tourist            London       2022-03-25
19             Canada   Tourist           Toronto       2022-12-21
20              India   Tourist         New Delhi       2022-04-07
33          Australia   Tourist        California       2022-09-06
35                 UK   Tourist         New Delhi       2022-11-20
39             Canada   Tourist           Toronto       2022-03-14
40                USA      Work         Hyderabad       2022-02-24
44            Germany      Work         Hyderabad       2022-11-11
50                 UK      Work         Hyderabad       2022-05-04
54             Canada      Work         New Delhi       2022-12-24
55          Australia      Work        California       2022-12-11
59                USA   Tourist            London       2022-01-11
60             France   Student         Hyderabad       2022-06-29
62             Canada      Work        California       2022-08-23
72             Canada      Work            Sydney       2022-04-13
79             France   Tourist        California       2022-02-08
84             Canada      Work            London       2022-08-11
86                 UK      Work           Toronto       2022-05-24
97             France   Tourist            Sydney       2022-04-02
102         Australia   Tourist         Hyderabad       2022-12-08
106         Australia   Tourist            Sydney       2022-05-09
107            Canada   Tourist        California       2022-07-01
116               USA      Work         New Delhi       2022-07-24
117            Canada   Student         New Delhi       2022-06-01
118             India   Tourist           Toronto       2022-12-19
119            Canada      Work        California       2022-08-08
121            France      Work            Sydney       2022-07-09
124             India   Student           Toronto       2022-10-08
128         Australia   Student            London       2022-09-19
144               USA      Work            London       2022-01-06

    Decision_Date  Applicant_Age  Experience_Years  Processing_Time_Days
0      2022-06-26             62              22.0                    99
4      2022-09-26             60              24.0                    23
6      2022-06-30             63               4.0                    97
19     2022-12-26             37              12.0                     5
20     2022-06-12             26              13.0                    66
33     2022-10-01             25              12.0                    25
35     2022-12-19             56              19.0                    29
39     2022-06-08             44              17.0                    86
40     2022-03-17             29               3.0                    21
44     2023-03-05             29              12.0                   114
50     2022-07-29             36              12.0                    86
54     2023-04-09             65              12.0                   106
55     2023-02-22             47              22.0                    73
59     2022-02-20             34              12.0                    40
60     2022-09-13             63              12.0                    76
62     2022-11-26             75              12.0                    95
72     2022-08-07             38               7.0                   116
79     2022-06-04             50              25.0                   116
84     2022-10-27             65              12.0                    77
86     2022-09-05             18               4.0                   104
97     2022-04-21             20              18.0                    19
102    2022-12-09             74              12.0                     1
106    2022-06-30             54              12.0                    52
107    2022-07-31             20              12.0                    30
116    2022-08-24             58              12.0                    31
117    2022-07-07             64              12.0                    36
118    2023-03-12             74              21.0                    83
119    2022-11-30             42              12.0                   114
121    2022-07-13             28              12.0                     4
124    2022-11-20             48               4.0                    43
128    2022-12-26             55               5.0                    98
144    2022-04-16             44              12.0                   100

C:\Users\Archana\AppData\Local\Temp\ipykernel_27976\3832303124.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['Application_ID'], inplace=True , errors= 'ignore')

In [58]:
df_encoded = pd.get_dummies(df, columns=['Applicant_Country', 'Visa_Type', 'Processing_Office'])
print("\n Encoded DataFrame:\n", df_encoded)

 Encoded DataFrame:
     Application_Date Decision_Date  Applicant_Age  Experience_Years  \
0         2022-03-19    2022-06-26             62              22.0
4         2022-09-03    2022-09-26             60              24.0
6         2022-03-25    2022-06-30             63               4.0
19        2022-12-21    2022-12-26             37              12.0
20        2022-04-07    2022-06-12             26              13.0
33        2022-09-06    2022-10-01             25              12.0
35        2022-11-20    2022-12-19             56              19.0
39        2022-03-14    2022-06-08             44              17.0
40        2022-02-24    2022-03-17             29               3.0
44        2022-11-11    2023-03-05             29              12.0
50        2022-05-04    2022-07-29             36              12.0
54        2022-12-24    2023-04-09             65              12.0
55        2022-12-11    2023-02-22             47              22.0
59        2022-01-11    2022-02-20             34              12.0
60        2022-06-29    2022-09-13             63              12.0
62        2022-08-23    2022-11-26             75              12.0
72        2022-04-13    2022-08-07             38               7.0
79        2022-02-08    2022-06-04             50              25.0
84        2022-08-11    2022-10-27             65              12.0
86        2022-05-24    2022-09-05             18               4.0
97        2022-04-02    2022-04-21             20              18.0
102       2022-12-08    2022-12-09             74              12.0
106       2022-05-09    2022-06-30             54              12.0
107       2022-07-01    2022-07-31             20              12.0
116       2022-07-24    2022-08-24             58              12.0
117       2022-06-01    2022-07-07             64              12.0
118       2022-12-19    2023-03-12             74              21.0
119       2022-08-08    2022-11-30             42              12.0
121       2022-07-09    2022-07-13             28              12.0
124       2022-10-08    2022-11-20             48               4.0
128       2022-09-19    2022-12-26             55               5.0
144       2022-01-06    2022-04-16             44              12.0

     Processing_Time_Days  Applicant_Country_Australia  \
0                      99                        False
4                      23                        False
6                      97                        False
19                      5                        False
20                     66                        False
33                     25                         True
35                     29                        False
39                     86                        False
40                     21                        False
44                    114                        False
50                     86                        False
54                    106                        False
55                     73                         True
59                     40                        False
60                     76                        False
62                     95                        False
72                    116                        False
79                    116                        False
84                     77                        False
86                    104                        False
97                     19                        False
102                     1                         True
106                    52                         True
107                    30                        False
116                    31                        False
117                    36                        False
118                    83                        False
119                   114                        False
121                     4                        False
124                    43                        False
128                    98                         True
144                   100                        False

     Applicant_Country_Canada  Applicant_Country_France  \
0                       False                     False
4                       False                     False
6                       False                     False
19                       True                     False
20                      False                     False
33                      False                     False
35                      False                     False
39                       True                     False
40                      False                     False
44                      False                     False
50                      False                     False
54                       True                     False
55                      False                     False
59                      False                     False
60                      False                      True
62                       True                     False
72                       True                     False
79                      False                      True
84                       True                     False
86                      False                     False
97                      False                      True
102                     False                     False
106                     False                     False
107                      True                     False
116                     False                     False
117                      True                     False
118                     False                     False
119                      True                     False
121                     False                      True
124                     False                     False
128                     False                     False
144                     False                     False

     Applicant_Country_Germany  Applicant_Country_India  ...  \
0                        False                    False  ...
4                         True                    False  ...
6                        False                    False  ...
19                       False                    False  ...
20                       False                     True  ...
33                       False                    False  ...
35                       False                    False  ...
39                       False                    False  ...
40                       False                    False  ...
44                        True                    False  ...
50                       False                    False  ...
54                       False                    False  ...
55                       False                    False  ...
59                       False                    False  ...
60                       False                    False  ...
62                       False                    False  ...
72                       False                    False  ...
79                       False                    False  ...
84                       False                    False  ...
86                       False                    False  ...
97                       False                    False  ...
102                      False                    False  ...
106                      False                    False  ...
107                      False                    False  ...
116                      False                    False  ...
117                      False                    False  ...
118                      False                     True  ...
119                      False                    False  ...
121                      False                    False  ...
124                      False                     True  ...
128                      False                    False  ...
144                      False                    False  ...

     Applicant_Country_USA  Visa_Type_Student  Visa_Type_Tourist  \
0                     True              False              False
4                    False              False              False
6                     True              False               True
19                   False              False               True
20                   False              False               True
33                   False              False               True
35                   False              False               True
39                   False              False               True
40                    True              False              False
44                   False              False              False
50                   False              False              False
54                   False              False              False
55                   False              False              False
59                    True              False               True
60                   False               True              False
62                   False              False              False
72                   False              False              False
79                   False              False               True
84                   False              False              False
86                   False              False              False
97                   False              False               True
102                  False              False               True
106                  False              False               True
107                  False              False               True
116                   True              False              False
117                  False               True              False
118                  False              False               True
119                  False              False              False
121                  False              False              False
124                  False               True              False
128                  False               True              False
144                   True              False              False

     Visa_Type_Work  Processing_Office_California  \
0              True                         False
4              True                         False
6             False                         False
19            False                         False
20            False                         False
33            False                          True
35            False                         False
39            False                         False
40             True                         False
44             True                         False
50             True                         False
54             True                         False
55             True                          True
59            False                         False
60            False                         False
62             True                          True
72             True                         False
79            False                          True
84             True                         False
86             True                         False
97            False                         False
102           False                         False
106           False                         False
107           False                          True
116            True                         False
117           False                         False
118           False                         False
119            True                          True
121            True                         False
124           False                         False
128           False                         False
144            True                         False

     Processing_Office_Hyderabad  Processing_Office_London  \
0                          False                      True
4                           True                     False
6                          False                      True
19                         False                     False
20                         False                     False
33                         False                     False
35                         False                     False
39                         False                     False
40                          True                     False
44                          True                     False
50                          True                     False
54                         False                     False
55                         False                     False
59                         False                      True
60                          True                     False
62                         False                     False
72                         False                     False
79                         False                     False
84                         False                      True
86                         False                     False
97                         False                     False
102                         True                     False
106                        False                     False
107                        False                     False
116                        False                     False
117                        False                     False
118                        False                     False
119                        False                     False
121                        False                     False
124                        False                     False
128                        False                      True
144                        False                      True

     Processing_Office_New Delhi  Processing_Office_Sydney  \
0                          False                     False
4                          False                     False
6                          False                     False
19                         False                     False
20                          True                     False
33                         False                     False
35                          True                     False
39                         False                     False
40                         False                     False
44                         False                     False
50                         False                     False
54                          True                     False
55                         False                     False
59                         False                     False
60                         False                     False
62                         False                     False
72                         False                      True
79                         False                     False
84                         False                     False
86                         False                     False
97                         False                      True
102                        False                     False
106                        False                      True
107                        False                     False
116                         True                     False
117                         True                     False
118                        False                     False
119                        False                     False
121                        False                      True
124                        False                     False
128                        False                     False
144                        False                     False

     Processing_Office_Toronto
0                        False
4                        False
6                        False
19                        True
20                       False
33                       False
35                       False
39                        True
40                       False
44                       False
50                       False
54                       False
55                       False
59                       False
60                       False
62                       False
72                       False
79                       False
84                       False
86                        True
97                       False
102                      False
106                      False
107                      False
116                      False
117                      False
118                       True
119                      False
121                      False
124                       True
128                      False
144                      False

[32 rows x 21 columns]

In [59]:
df.to_csv("cleaned_visa_data.csv", index=False)